import { describe, expect, it, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { writeEnvFile, writeEnvFileWithMeta } from "./env-wizard.js";
import type { EnvVar } from "./registry.js";

// ---------- writeEnvFile ----------

describe("writeEnvFile", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "open-scaffolds-env-test-"));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("writes correct .env format to temp dir", () => {
    const values = {
      DATABASE_URL: "postgres://localhost:5432/mydb",
      APP_NAME: "myapp",
      PORT: "3000",
    };

    const envPath = writeEnvFile(values, tmpDir);
    expect(envPath).toBe(join(tmpDir, ".env"));

    const content = readFileSync(envPath, "utf-8");
    // Header comment
    expect(content).toContain("# .env — generated by open-scaffolds");
    // Plain values without spaces or special chars — no quotes
    expect(content).toContain("APP_NAME=myapp");
    expect(content).toContain("PORT=3000");
    // URL without spaces — no quotes needed
    expect(content).toContain("DATABASE_URL=postgres://localhost:5432/mydb");
  });

  it("quotes values that contain spaces", () => {
    const values = { GREETING: "hello world" };
    const envPath = writeEnvFile(values, tmpDir);
    const content = readFileSync(envPath, "utf-8");
    expect(content).toContain('GREETING="hello world"');
  });

  it("quotes values containing hash characters", () => {
    const values = { COLOR: "#ffffff" };
    const envPath = writeEnvFile(values, tmpDir);
    const content = readFileSync(envPath, "utf-8");
    expect(content).toContain('COLOR="#ffffff"');
  });

  it("writes secret values — does not skip them", () => {
    const values = { SECRET_KEY: "super-secret-value-123" };
    const envPath = writeEnvFile(values, tmpDir);
    const content = readFileSync(envPath, "utf-8");
    expect(content).toContain("SECRET_KEY=super-secret-value-123");
  });

  it("returns the absolute path to the written .env file", () => {
    const envPath = writeEnvFile({ FOO: "bar" }, tmpDir);
    expect(envPath).toBe(join(tmpDir, ".env"));
  });

  it("handles empty values object", () => {
    const envPath = writeEnvFile({}, tmpDir);
    const content = readFileSync(envPath, "utf-8");
    expect(content).toContain("# .env — generated by open-scaffolds");
  });
});

// ---------- writeEnvFileWithMeta ----------

describe("writeEnvFileWithMeta", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "open-scaffolds-meta-test-"));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  const makeVar = (
    key: string,
    group: string,
    opts: Partial<EnvVar> = {}
  ): EnvVar => ({
    key,
    label: key,
    description: `Description for ${key}`,
    required: true,
    secret: false,
    group,
    ...opts,
  });

  it("groups vars by group with section comments", () => {
    const vars: EnvVar[] = [
      makeVar("DATABASE_URL", "Database"),
      makeVar("REDIS_URL", "Database"),
      makeVar("STRIPE_KEY", "Billing"),
    ];

    const values = {
      DATABASE_URL: "postgres://localhost/db",
      REDIS_URL: "redis://localhost:6379",
      STRIPE_KEY: "sk_test_123",
    };

    const envPath = writeEnvFileWithMeta(values, vars, tmpDir);
    const content = readFileSync(envPath, "utf-8");

    // Section headers for each group
    expect(content).toContain("# ── Database");
    expect(content).toContain("# ── Billing");
    // Vars in sections — URLs have no spaces/special chars so no quotes
    expect(content).toContain("DATABASE_URL=postgres://localhost/db");
    expect(content).toContain("REDIS_URL=redis://localhost:6379");
    expect(content).toContain("STRIPE_KEY=sk_test_123");
  });

  it("skips vars with no value in the values map", () => {
    const vars: EnvVar[] = [
      makeVar("DATABASE_URL", "Database"),
      makeVar("OPTIONAL_KEY", "Optional"),
    ];

    const values = {
      DATABASE_URL: "postgres://localhost/db",
      // OPTIONAL_KEY intentionally omitted
    };

    const envPath = writeEnvFileWithMeta(values, vars, tmpDir);
    const content = readFileSync(envPath, "utf-8");

    expect(content).toContain("DATABASE_URL");
    expect(content).not.toContain("OPTIONAL_KEY");
    // Optional section header should not appear if all vars are skipped
    expect(content).not.toContain("# ── Optional");
  });

  it("writes secret values without masking them in the file", () => {
    const vars: EnvVar[] = [
      makeVar("API_SECRET", "Secrets", { secret: true }),
    ];

    const values = { API_SECRET: "my-real-secret-value" };

    const envPath = writeEnvFileWithMeta(values, vars, tmpDir);
    const content = readFileSync(envPath, "utf-8");

    // Actual value must be written to file (not masked as ***)
    expect(content).toContain("API_SECRET=my-real-secret-value");
    expect(content).not.toContain("***");
  });

  it("returns the absolute path to the .env file", () => {
    const envPath = writeEnvFileWithMeta({}, [], tmpDir);
    expect(envPath).toBe(join(tmpDir, ".env"));
  });

  it("preserves group insertion order", () => {
    const vars: EnvVar[] = [
      makeVar("A_KEY", "GroupA"),
      makeVar("B_KEY", "GroupB"),
      makeVar("C_KEY", "GroupC"),
    ];

    const values = { A_KEY: "a", B_KEY: "b", C_KEY: "c" };

    const envPath = writeEnvFileWithMeta(values, vars, tmpDir);
    const content = readFileSync(envPath, "utf-8");

    const posA = content.indexOf("GroupA");
    const posB = content.indexOf("GroupB");
    const posC = content.indexOf("GroupC");

    expect(posA).toBeLessThan(posB);
    expect(posB).toBeLessThan(posC);
  });
});
